server:
  port: 8888
  servlet:
    context-path: /hc

spring.mvc:


hc: 韩闯

#前端视图展示,使用jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/JSP/  #前缀,在webapp路径下/WEB-INF/JSP/文件夹中
      suffix: .jsp          #后缀


  datasource:
    url: jdbc:mysql://localhost:3306/dw
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.hanchuang.entity
  mapperLocations: classpath:mapper/*.xml